base:
  project: KaggleHousingPrices 
  random_state: 10
  target_col: SalePrice


data_source:
  input_data_dir: data
  output_data_dir: results


training_data_preparation:
  data_dir: data/interim 
  raw_data_file: train.csv
  raw_data_fpath: data/interim/train.csv
  validated_raw_data_fpath: data/interim/train_validated.csv
  not_validated_raw_data_fpath: data/interim/train_not_validated.csv
  categorical_converted_data_fpath: data/interim/train_treated_categorical_converted.csv
  missing_value_imputed_data_fpath: data/interim/train_treated_missing_imputed.csv
  new_features_created_data_fpath: data/interim/train_treated_new_features_created.csv
  outliers_treated_data_fpath: data/interim/train_treated_outliers_handled.csv
  schema_training: config/schema_training.json
  master_csv_fpath: data/processed/master_train.csv


test_data_preparation:
  data_dir: data/interim 
  raw_data_file: test.csv
  raw_data_fpath: data/interim/test.csv
  validated_raw_data_fpath: data/interim/test_validated.csv
  not_validated_raw_data_fpath: data/interim/test_not_validated.csv
  treated_data_fpath: data/interim/test_treated.csv
  schema_test: config/schema_test.json 
  master_csv_fpath: data/processed/master_test.csv
  prediction_fpath: results/submission.csv


saved_models:
  model_dir: models


data_preprocessing:

  KNNImputer: 
    k: 50 


artifacts_dir: 
  general: general
  mlflow: mlflow_artifacts


training:
  random_forest:
    cv: 5
    verbose: 3
    param_grid:
      n_estimators: 
        - 10
        - 50
        - 100
        - 130 
      criterion: 
        - gini
        - entropy
      max_depth: 
        - 2
        - 4
      max_features: 
        - auto
        - log2
  xg_boost:
    cv: 5
    verbose: 3
    param_grid:
      learning_rate: 
        - 0.5
        - 0.1
        - 0.01
        - 0.001
      max_depth: 
        - 3
        - 5
        - 10
        - 20
      n_estimators: 
        - 10
        - 50
        - 100
        - 200
